/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.14.0.75.2 */
/* Module Version: 5.8 */
/* C:\lscc\diamond\3.14\ispfpga\bin\nt64\scuba.exe -w -n mipi_dsi_tx -lang verilog -synth lse -bus_exp 7 -bb -arch sn5w00 -type iol -io_type LVDS -mode MIPI -freq_in 500 -width 4 -app DSI_TX_H -gear 16 -pll 50  */
/* Mon Feb 02 09:05:13 2026 */


`timescale 1 ns / 1 ps
module mipi_dsi_tx (clk_n, clk_p, clk_txhsen, clk_txhsgate, clk_txlpen, 
    clk_txlpn, clk_txlpp, d0_rxlpn, d0_rxlpp, d0_txhsen, d0_txlpen, 
    d0_txlpn, d0_txlpp, d1_txlpn, d1_txlpp, d2_txlpn, d2_txlpp, d3_txlpn, 
    d3_txlpp, lock, pd_pll, refclk, txhsbyteclk, usrstdby, data_n, 
    data_p, txdata)/* synthesis NGD_DRC_MASK=1 */;
    input wire clk_txhsen;
    input wire clk_txhsgate;
    input wire clk_txlpen;
    input wire clk_txlpn;
    input wire clk_txlpp;
    input wire d0_txhsen;
    input wire d0_txlpen;
    input wire d0_txlpn;
    input wire d0_txlpp;
    input wire d1_txlpn;
    input wire d1_txlpp;
    input wire d2_txlpn;
    input wire d2_txlpp;
    input wire d3_txlpn;
    input wire d3_txlpp;
    input wire pd_pll;
    input wire refclk;
    input wire usrstdby;
    input wire [63:0] txdata;
    output wire d0_rxlpn;
    output wire d0_rxlpp;
    output wire lock;
    output wire txhsbyteclk;
    inout wire clk_n;
    inout wire clk_p;
    inout wire [3:0] data_n;
    inout wire [3:0] data_p;

    wire clk_txhsen_inv;
    wire d0_txlpen_inv;
    wire d0_txhsen_inv;
    wire d0txlpen;
    wire d0rxlpen;
    wire clktxlpen;
    wire scuba_vlo;
    wire pllclki;
    wire dp3;
    wire dp2;
    wire dp1;
    wire dp0;
    wire do3;
    wire do2;
    wire do1;
    wire do0;
    wire dn3;
    wire dn2;
    wire dn1;
    wire dn0;
    wire dm3;
    wire dm2;
    wire dm1;
    wire dm0;
    wire dl3;
    wire dl2;
    wire dl1;
    wire dl0;
    wire dk3;
    wire dk2;
    wire dk1;
    wire dk0;
    wire dj3;
    wire dj2;
    wire dj1;
    wire dj0;
    wire di3;
    wire di2;
    wire di1;
    wire di0;
    wire dh3;
    wire dh2;
    wire dh1;
    wire dh0;
    wire dg3;
    wire dg2;
    wire dg1;
    wire dg0;
    wire df3;
    wire df2;
    wire df1;
    wire df0;
    wire de3;
    wire de2;
    wire de1;
    wire de0;
    wire dd3;
    wire dd2;
    wire dd1;
    wire dd0;
    wire dc3;
    wire dc2;
    wire dc1;
    wire dc0;
    wire db3;
    wire db2;
    wire db1;
    wire db0;
    wire da3;
    wire da2;
    wire da1;
    wire da0;

    INV INV_2 (.A(clk_txhsen), .Z(clk_txhsen_inv));

    AND2 AND2_t2 (.A(clk_txhsen_inv), .B(clk_txlpen), .Z(clktxlpen));

    INV INV_1 (.A(d0_txhsen), .Z(d0_txhsen_inv));

    AND2 AND2_t1 (.A(d0_txhsen_inv), .B(d0_txlpen), .Z(d0txlpen));

    INV INV_0 (.A(d0_txlpen), .Z(d0_txlpen_inv));

    AND2 AND2_t0 (.A(d0_txhsen_inv), .B(d0_txlpen_inv), .Z(d0rxlpen));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    defparam Inst_MIPIDPHYA.HS_16BIT_EN = 1 ;
    defparam Inst_MIPIDPHYA.HSEL = 0 ;
    defparam Inst_MIPIDPHYA.CO = 0 ;
    defparam Inst_MIPIDPHYA.CM = 200 ;
    defparam Inst_MIPIDPHYA.CN = 0 ;
    MIPIDPHYA Inst_MIPIDPHYA (.CKP(clk_p), .CKN(clk_n), .CLKHSBYTE(), .CLKRXHSEN(scuba_vlo), 
        .CLKDRXLPP(), .CLKRXLPEN(scuba_vlo), .CLKDRXLPN(), .CLKCDEN(scuba_vlo), 
        .CLKDCDN(), .CLKDTXLPP(clk_txlpp), .CLKTXLPEN(clktxlpen), .CLKDTXLPN(clk_txlpn), 
        .CLKTXHSEN(clk_txhsen), .CLKTXHSGATE(clk_txhsgate), .CLKTXHSPD(scuba_vlo), 
        .CLKDRXHS(), .HSBYTECLKD(), .HSBYTECLKS(txhsbyteclk), .LBEN(scuba_vlo), 
        .PDDPHY(usrstdby), .PDBIAS(usrstdby), .PDCKG(usrstdby), .CLKREF(pllclki), 
        .LOCK(lock), .PDPLL(pd_pll), .DP0(data_p[0]), .DP1(data_p[1]), .DP2(data_p[2]), 
        .DP3(data_p[3]), .DN0(data_n[0]), .DN1(data_n[1]), .DN2(data_n[2]), 
        .DN3(data_n[3]), .D0DRXLPP(d0_rxlpp), .D0RXLPEN(d0rxlpen), .D0DRXLPN(d0_rxlpn), 
        .D0DCDP(), .D0CDEN(scuba_vlo), .D0DCDN(), .D0DTXLPP(d0_txlpp), .D0TXLPEN(d0txlpen), 
        .D0DTXLPN(d0_txlpn), .D0RXHSEN(scuba_vlo), .D0HSRXDATA15(), .D0HSRXDATA14(), 
        .D0HSRXDATA13(), .D0HSRXDATA12(), .D0HSRXDATA11(), .D0HSRXDATA10(), 
        .D0HSRXDATA9(), .D0HSRXDATA8(), .D0HSRXDATA7(), .D0HSRXDATA6(), 
        .D0HSRXDATA5(), .D0HSRXDATA4(), .D0HSRXDATA3(), .D0HSRXDATA2(), 
        .D0HSRXDATA1(), .D0HSRXDATA0(), .D0SYNC(), .D0ERRSYNC(), .D0NOSYNC(), 
        .D0HSDESEREN(scuba_vlo), .D0TXHSEN(d0_txhsen), .D0HSTXDATA15(dp0), 
        .D0HSTXDATA14(do0), .D0HSTXDATA13(dn0), .D0HSTXDATA12(dm0), .D0HSTXDATA11(dl0), 
        .D0HSTXDATA10(dk0), .D0HSTXDATA9(dj0), .D0HSTXDATA8(di0), .D0HSTXDATA7(dh0), 
        .D0HSTXDATA6(dg0), .D0HSTXDATA5(df0), .D0HSTXDATA4(de0), .D0HSTXDATA3(dd0), 
        .D0HSTXDATA2(dc0), .D0HSTXDATA1(db0), .D0HSTXDATA0(da0), .D0HSSEREN(d0_txhsen), 
        .D0TXHSPD(scuba_vlo), .D0DRXHS(), .D1DRXLPP(), .D1RXLPEN(scuba_vlo), 
        .D1DRXLPN(), .D1DCDP(), .D1CDEN(scuba_vlo), .D1DCDN(), .D1DTXLPP(d1_txlpp), 
        .D1TXLPEN(d0txlpen), .D1DTXLPN(d1_txlpn), .D1RXHSEN(scuba_vlo), 
        .D1HSRXDATA15(), .D1HSRXDATA14(), .D1HSRXDATA13(), .D1HSRXDATA12(), 
        .D1HSRXDATA11(), .D1HSRXDATA10(), .D1HSRXDATA9(), .D1HSRXDATA8(), 
        .D1HSRXDATA7(), .D1HSRXDATA6(), .D1HSRXDATA5(), .D1HSRXDATA4(), 
        .D1HSRXDATA3(), .D1HSRXDATA2(), .D1HSRXDATA1(), .D1HSRXDATA0(), 
        .D1SYNC(), .D1ERRSYNC(), .D1NOSYNC(), .D1HSDESEREN(scuba_vlo), .D1TXHSEN(d0_txhsen), 
        .D1HSTXDATA15(dp1), .D1HSTXDATA14(do1), .D1HSTXDATA13(dn1), .D1HSTXDATA12(dm1), 
        .D1HSTXDATA11(dl1), .D1HSTXDATA10(dk1), .D1HSTXDATA9(dj1), .D1HSTXDATA8(di1), 
        .D1HSTXDATA7(dh1), .D1HSTXDATA6(dg1), .D1HSTXDATA5(df1), .D1HSTXDATA4(de1), 
        .D1HSTXDATA3(dd1), .D1HSTXDATA2(dc1), .D1HSTXDATA1(db1), .D1HSTXDATA0(da1), 
        .D1HSSEREN(d0_txhsen), .D1TXHSPD(scuba_vlo), .D1DRXHS(), .D2DRXLPP(), 
        .D2RXLPEN(scuba_vlo), .D2DRXLPN(), .D2DCDP(), .D2CDEN(scuba_vlo), 
        .D2DCDN(), .D2DTXLPP(d2_txlpp), .D2TXLPEN(d0txlpen), .D2DTXLPN(d2_txlpn), 
        .D2RXHSEN(scuba_vlo), .D2HSRXDATA15(), .D2HSRXDATA14(), .D2HSRXDATA13(), 
        .D2HSRXDATA12(), .D2HSRXDATA11(), .D2HSRXDATA10(), .D2HSRXDATA9(), 
        .D2HSRXDATA8(), .D2HSRXDATA7(), .D2HSRXDATA6(), .D2HSRXDATA5(), 
        .D2HSRXDATA4(), .D2HSRXDATA3(), .D2HSRXDATA2(), .D2HSRXDATA1(), 
        .D2HSRXDATA0(), .D2SYNC(), .D2ERRSYNC(), .D2NOSYNC(), .D2HSDESEREN(scuba_vlo), 
        .D2TXHSEN(d0_txhsen), .D2HSTXDATA15(dp2), .D2HSTXDATA14(do2), .D2HSTXDATA13(dn2), 
        .D2HSTXDATA12(dm2), .D2HSTXDATA11(dl2), .D2HSTXDATA10(dk2), .D2HSTXDATA9(dj2), 
        .D2HSTXDATA8(di2), .D2HSTXDATA7(dh2), .D2HSTXDATA6(dg2), .D2HSTXDATA5(df2), 
        .D2HSTXDATA4(de2), .D2HSTXDATA3(dd2), .D2HSTXDATA2(dc2), .D2HSTXDATA1(db2), 
        .D2HSTXDATA0(da2), .D2HSSEREN(d0_txhsen), .D2TXHSPD(scuba_vlo), 
        .D2DRXHS(), .D3DRXLPP(), .D3RXLPEN(scuba_vlo), .D3DRXLPN(), .D3DCDP(), 
        .D3CDEN(scuba_vlo), .D3DCDN(), .D3DTXLPP(d3_txlpp), .D3TXLPEN(d0txlpen), 
        .D3DTXLPN(d3_txlpn), .D3RXHSEN(scuba_vlo), .D3HSRXDATA15(), .D3HSRXDATA14(), 
        .D3HSRXDATA13(), .D3HSRXDATA12(), .D3HSRXDATA11(), .D3HSRXDATA10(), 
        .D3HSRXDATA9(), .D3HSRXDATA8(), .D3HSRXDATA7(), .D3HSRXDATA6(), 
        .D3HSRXDATA5(), .D3HSRXDATA4(), .D3HSRXDATA3(), .D3HSRXDATA2(), 
        .D3HSRXDATA1(), .D3HSRXDATA0(), .D3SYNC(), .D3ERRSYNC(), .D3NOSYNC(), 
        .D3HSDESEREN(scuba_vlo), .D3TXHSEN(d0_txhsen), .D3HSTXDATA15(dp3), 
        .D3HSTXDATA14(do3), .D3HSTXDATA13(dn3), .D3HSTXDATA12(dm3), .D3HSTXDATA11(dl3), 
        .D3HSTXDATA10(dk3), .D3HSTXDATA9(dj3), .D3HSTXDATA8(di3), .D3HSTXDATA7(dh3), 
        .D3HSTXDATA6(dg3), .D3HSTXDATA5(df3), .D3HSTXDATA4(de3), .D3HSTXDATA3(dd3), 
        .D3HSTXDATA2(dc3), .D3HSTXDATA1(db3), .D3HSTXDATA0(da3), .D3HSSEREN(d0_txhsen), 
        .D3TXHSPD(scuba_vlo), .D3DRXHS())
             /* synthesis HS_MODE="TX" */
             /* synthesis DIR_PIN_DN3="OUTPUT" */
             /* synthesis DIR_PIN_DP3="OUTPUT" */
             /* synthesis DIR_PIN_DN2="OUTPUT" */
             /* synthesis DIR_PIN_DP2="OUTPUT" */
             /* synthesis DIR_PIN_DN1="OUTPUT" */
             /* synthesis DIR_PIN_DP1="OUTPUT" */
             /* synthesis DIR_PIN_CKN="OUTPUT" */
             /* synthesis DIR_PIN_CKP="OUTPUT" */
             /* synthesis FREQUENCY_PIN_HSBYTECLKS="62.500000" */
             /* synthesis FREQUENCY_PIN_CKN="500.000000" */
             /* synthesis FREQUENCY_PIN_CKP="500.000000" */
             /* synthesis FREQUENCY_PIN_CLKREF="50.000000" */;

    assign pllclki = refclk;
    assign dp3 = txdata[63];
    assign dp2 = txdata[62];
    assign dp1 = txdata[61];
    assign dp0 = txdata[60];
    assign do3 = txdata[59];
    assign do2 = txdata[58];
    assign do1 = txdata[57];
    assign do0 = txdata[56];
    assign dn3 = txdata[55];
    assign dn2 = txdata[54];
    assign dn1 = txdata[53];
    assign dn0 = txdata[52];
    assign dm3 = txdata[51];
    assign dm2 = txdata[50];
    assign dm1 = txdata[49];
    assign dm0 = txdata[48];
    assign dl3 = txdata[47];
    assign dl2 = txdata[46];
    assign dl1 = txdata[45];
    assign dl0 = txdata[44];
    assign dk3 = txdata[43];
    assign dk2 = txdata[42];
    assign dk1 = txdata[41];
    assign dk0 = txdata[40];
    assign dj3 = txdata[39];
    assign dj2 = txdata[38];
    assign dj1 = txdata[37];
    assign dj0 = txdata[36];
    assign di3 = txdata[35];
    assign di2 = txdata[34];
    assign di1 = txdata[33];
    assign di0 = txdata[32];
    assign dh3 = txdata[31];
    assign dh2 = txdata[30];
    assign dh1 = txdata[29];
    assign dh0 = txdata[28];
    assign dg3 = txdata[27];
    assign dg2 = txdata[26];
    assign dg1 = txdata[25];
    assign dg0 = txdata[24];
    assign df3 = txdata[23];
    assign df2 = txdata[22];
    assign df1 = txdata[21];
    assign df0 = txdata[20];
    assign de3 = txdata[19];
    assign de2 = txdata[18];
    assign de1 = txdata[17];
    assign de0 = txdata[16];
    assign dd3 = txdata[15];
    assign dd2 = txdata[14];
    assign dd1 = txdata[13];
    assign dd0 = txdata[12];
    assign dc3 = txdata[11];
    assign dc2 = txdata[10];
    assign dc1 = txdata[9];
    assign dc0 = txdata[8];
    assign db3 = txdata[7];
    assign db2 = txdata[6];
    assign db1 = txdata[5];
    assign db0 = txdata[4];
    assign da3 = txdata[3];
    assign da2 = txdata[2];
    assign da1 = txdata[1];
    assign da0 = txdata[0];


    // exemplar begin
    // exemplar attribute Inst_MIPIDPHYA HS_MODE TX
    // exemplar attribute Inst_MIPIDPHYA DIR_PIN_DN3 OUTPUT
    // exemplar attribute Inst_MIPIDPHYA DIR_PIN_DP3 OUTPUT
    // exemplar attribute Inst_MIPIDPHYA DIR_PIN_DN2 OUTPUT
    // exemplar attribute Inst_MIPIDPHYA DIR_PIN_DP2 OUTPUT
    // exemplar attribute Inst_MIPIDPHYA DIR_PIN_DN1 OUTPUT
    // exemplar attribute Inst_MIPIDPHYA DIR_PIN_DP1 OUTPUT
    // exemplar attribute Inst_MIPIDPHYA DIR_PIN_CKN OUTPUT
    // exemplar attribute Inst_MIPIDPHYA DIR_PIN_CKP OUTPUT
    // exemplar attribute Inst_MIPIDPHYA FREQUENCY_PIN_HSBYTECLKS 62.500000
    // exemplar attribute Inst_MIPIDPHYA FREQUENCY_PIN_CKN 500.000000
    // exemplar attribute Inst_MIPIDPHYA FREQUENCY_PIN_CKP 500.000000
    // exemplar attribute Inst_MIPIDPHYA FREQUENCY_PIN_CLKREF 50.000000
    // exemplar end

endmodule
